[package]
name = "tachyon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
tachyon-compiler = { path = "../tachyon-compiler" }
tachyon-vm = { path = "../tachyon-vm" }

[dev-dependencies]
tachyon-value = { path = "../tachyon-value" }
