[workspace]
members = [
    "crates/tachyon-value",
    "crates/tachyon-bytecode",
    "crates/tachyon-gc",
    "crates/tachyon-compiler",
    "crates/tachyon-vm",
    "crates/tachyon-intl-icu4x",
    "crates/tachyon",
    "tools/tachyon-cli",
    "tools/benchmark-runner",
    "tools/test262-runner",
    "tools/xtask",
]
default-members = [
    "crates/tachyon",
    "tools/tachyon-cli",
    "tools/xtask",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.95"
version = "0.1.0"
license = "Apache-2.0"
repository = "https://github.com/lemonhx/tachyon-js"

[profile.dev]
opt-level = 3
debug = 2
debug-assertions = false
overflow-checks = false
panic = "abort"

[profile.test]
opt-level = 3
debug = 2
debug-assertions = false
overflow-checks = false

[profile.release]
codegen-units = 1
lto = "thin"
debug = 2
panic = "abort"

[profile.bench]
codegen-units = 1
lto = "thin"
debug = 2
