[package]
name = "tachyon-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
oxc = { version = "=0.140.0", features = ["ast_visit", "semantic"] }
ryu-js = "=1.0.3"
tachyon-bytecode = { path = "../tachyon-bytecode" }

[dev-dependencies]
proptest = "1.6"
