[package]
name = "tachyon-intl-icu4x"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
fixed_decimal = { version = "=0.7.2", default-features = false }
icu_calendar = { version = "=2.0.6", default-features = false, features = ["compiled_data"] }
icu_collator = { version = "=2.0.0", default-features = false, features = ["compiled_data"] }
icu_decimal = { version = "=2.0.0", default-features = false, features = ["alloc", "compiled_data"] }
icu_locale = { version = "=2.0.0", default-features = false, features = ["compiled_data"] }
icu_locale_core = { version = "=2.0.0", default-features = false }
icu_list = { version = "=2.0.0", default-features = false, features = ["compiled_data"] }
icu_plurals = { version = "=2.0.0", default-features = false, features = ["compiled_data"] }
icu_provider = { version = "=2.0.0", default-features = false }
icu_time = { version = "=2.0.0", default-features = false, features = ["compiled_data"] }
tachyon-vm = { path = "../tachyon-vm" }
writeable = { version = "=0.6.3", default-features = false, features = ["alloc"] }
