//! ECMAScript builtin slow-path implementations.

mod array;
mod array_buffer;
mod atomics;
mod bigint;
mod boolean;
mod collections;
mod data_view;
mod date;
mod finalization_registry;
mod function;
mod global;
mod intl;
mod intl_collator;
mod intl_date_time_format;
mod intl_date_time_format_range;
mod intl_display_names;
mod intl_list_format;
mod intl_locale;
mod intl_number_format;
mod intl_number_format_options;
mod intl_plural_rules;
mod intl_relative_time_format;
mod json;
mod map_upsert;
mod math;
pub(crate) mod object;
mod promise_combinator;
mod regexp;
mod shared_array_buffer;
pub(crate) use regexp::append_regexp_replacement;
pub(crate) mod signals;
mod string;
mod symbol;
pub(crate) mod typed_array;
mod uri;
mod weak_collections;
mod weak_ref;

pub(crate) use date::PendingDateNumericArguments;
pub(crate) use intl_collator::PendingIntlCollator;
pub(crate) use intl_date_time_format::{DateTimeLocaleKind, PendingIntlDateTimeFormat};
pub(crate) use intl_display_names::PendingIntlDisplayNames;
pub(crate) use intl_list_format::PendingIntlListFormat;
pub(crate) use intl_locale::PendingIntlLocale;
pub(crate) use intl_number_format_options::PendingIntlNumberFormat;
pub(crate) use intl_plural_rules::PendingIntlPluralRules;
pub(crate) use intl_relative_time_format::PendingIntlRelativeTimeFormat;
pub(crate) use json::PendingJsonStringify;
pub(crate) use math::{math_variadic_add, math_variadic_finish, math_variadic_initial};
pub(crate) use regexp::advance_regexp_split_index;
