use core::fmt;

use serde::{Deserialize, Deserializer, Serialize, Serializer};

/// The specification phase in which a negative test must fail.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Phase {
    /// Source text parsing and early errors.
    Parse,
    /// Module graph resolution and linking.
    Resolution,
    /// Script or module evaluation.
    Runtime,
}

/// A negative Test262 expectation. Error names remain strings to tolerate future standard errors.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NegativeExpectation {
    /// Exact phase in which evaluation must fail.
    pub phase: Phase,
    #[serde(rename = "type")]
    /// ECMAScript error constructor name required by Test262.
    pub error_type: Box<str>,
}

/// A known execution flag or an explicitly retained future Test262 flag.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum TestFlag {
    /// Execute only with an injected strict directive.
    OnlyStrict,
    /// Execute only as a non-strict script.
    NoStrict,
    /// Parse and evaluate as a module.
    Module,
    /// Do not install implicit harness sources.
    Raw,
    /// Wait for the Test262 asynchronous completion protocol.
    Async,
    /// Test was generated by upstream tooling.
    Generated,
    /// Host blocking operations must be disabled.
    CanBlockIsFalse,
    /// Host blocking operations are explicitly allowed.
    CanBlockIsTrue,
    /// Result may vary between otherwise equivalent executions.
    NonDeterministic,
    /// A future flag retained for a structured compatibility error.
    Unknown(Box<str>),
}

/// Parsed YAML frontmatter independent from any engine representation.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct TestMetadata {
    /// Required upstream description.
    pub description: Box<str>,
    #[serde(default)]
    /// Current specification algorithm identifier.
    pub esid: Option<Box<str>>,
    #[serde(default)]
    /// Legacy ES5 algorithm identifier.
    pub es5id: Option<Box<str>>,
    #[serde(default)]
    /// Legacy ES6 algorithm identifier.
    pub es6id: Option<Box<str>>,
    #[serde(default)]
    /// Extended upstream rationale or algorithm notes.
    pub info: Box<str>,
    #[serde(default)]
    /// Feature tags used for applicability and edition classification.
    pub features: Vec<Box<str>>,
    #[serde(default)]
    /// Additional harness sources evaluated in declaration order.
    pub includes: Vec<Box<str>>,
    #[serde(default)]
    /// Execution and host policy flags.
    pub flags: Vec<TestFlag>,
    #[serde(default)]
    /// Expected phase/type for a negative test.
    pub negative: Option<NegativeExpectation>,
    #[serde(default)]
    /// Locale list required by ECMA-402 tests.
    pub locale: Vec<Box<str>>,
}

/// One independently counted strict, non-strict, module, or raw execution.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum VariantKind {
    /// Non-strict script execution.
    Sloppy,
    /// Script execution with an injected strict directive.
    Strict,
    /// Module parse/link/evaluate execution.
    Module,
    /// Raw script execution without implicit harness sources.
    Raw,
}

/// The source transformation and host policy selected for one Test262 variant.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct TestVariant {
    /// Script/module and strictness mode.
    pub kind: VariantKind,
    /// Whether the async completion harness applies.
    pub is_async: bool,
    /// Host blocking policy from Test262 flags.
    pub can_block: bool,
    /// Whether standard and declared harness sources are installed.
    pub use_harness: bool,
}

/// Frontmatter extraction or YAML decoding failed without panicking on malformed source.
#[derive(Debug)]
pub enum FrontmatterError {
    /// The opening metadata delimiter is absent.
    MissingStart,
    /// The closing metadata delimiter is absent.
    MissingEnd,
    /// YAML decoding rejected the bounded frontmatter text.
    InvalidYaml(serde_saphyr::Error),
}

/// Test flags describe an impossible or ambiguous execution matrix.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum VariantError {
    /// `onlyStrict` and `noStrict` cannot both select a script mode.
    ConflictingStrictness,
    /// Upstream introduced a flag whose semantics are not yet modeled.
    UnknownFlag(Box<str>),
}

impl TestMetadata {
    /// Extracts exactly one `/*--- ... ---*/` block and normalizes CRLF only for YAML parsing.
    pub fn parse(source: &str) -> Result<Self, FrontmatterError> {
        let start = source.find("/*---").ok_or(FrontmatterError::MissingStart)? + 5;
        let tail = &source[start..];
        let end = tail.find("---*/").ok_or(FrontmatterError::MissingEnd)?;
        let yaml = &tail[..end];
        if yaml.contains('\r') {
            serde_saphyr::from_str(&yaml.replace('\r', "\n")).map_err(FrontmatterError::InvalidYaml)
        } else {
            serde_saphyr::from_str(yaml).map_err(FrontmatterError::InvalidYaml)
        }
    }

    /// Expands flags into independently counted variants using Test262 strict-mode rules.
    pub fn variants(&self) -> Result<Vec<TestVariant>, VariantError> {
        for flag in &self.flags {
            if let TestFlag::Unknown(name) = flag {
                return Err(VariantError::UnknownFlag(name.clone()));
            }
        }
        let raw = self.has_flag(&TestFlag::Raw);
        let module = self.has_flag(&TestFlag::Module);
        let only_strict = self.has_flag(&TestFlag::OnlyStrict);
        let no_strict = self.has_flag(&TestFlag::NoStrict);
        if only_strict && no_strict {
            return Err(VariantError::ConflictingStrictness);
        }
        let is_async = self.has_flag(&TestFlag::Async);
        let can_block = !self.has_flag(&TestFlag::CanBlockIsFalse);
        let variant = |kind| TestVariant {
            kind,
            is_async,
            can_block,
            use_harness: !raw,
        };
        if module {
            return Ok(vec![variant(VariantKind::Module)]);
        }
        if raw {
            return Ok(vec![variant(VariantKind::Raw)]);
        }
        if only_strict {
            return Ok(vec![variant(VariantKind::Strict)]);
        }
        if no_strict {
            return Ok(vec![variant(VariantKind::Sloppy)]);
        }
        Ok(vec![
            variant(VariantKind::Sloppy),
            variant(VariantKind::Strict),
        ])
    }

    fn has_flag(&self, expected: &TestFlag) -> bool {
        self.flags.iter().any(|flag| flag == expected)
    }
}

impl TestFlag {
    fn parse(value: &str) -> Self {
        match value {
            "onlyStrict" => Self::OnlyStrict,
            "noStrict" => Self::NoStrict,
            "module" => Self::Module,
            "raw" => Self::Raw,
            "async" => Self::Async,
            "generated" => Self::Generated,
            "CanBlockIsFalse" => Self::CanBlockIsFalse,
            "CanBlockIsTrue" => Self::CanBlockIsTrue,
            "non-deterministic" => Self::NonDeterministic,
            unknown => Self::Unknown(unknown.into()),
        }
    }

    fn as_str(&self) -> &str {
        match self {
            Self::OnlyStrict => "onlyStrict",
            Self::NoStrict => "noStrict",
            Self::Module => "module",
            Self::Raw => "raw",
            Self::Async => "async",
            Self::Generated => "generated",
            Self::CanBlockIsFalse => "CanBlockIsFalse",
            Self::CanBlockIsTrue => "CanBlockIsTrue",
            Self::NonDeterministic => "non-deterministic",
            Self::Unknown(value) => value,
        }
    }
}

impl<'de> Deserialize<'de> for TestFlag {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = Box::<str>::deserialize(deserializer)?;
        Ok(Self::parse(&value))
    }
}

impl Serialize for TestFlag {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl fmt::Display for FrontmatterError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingStart => formatter.write_str("test source has no /*--- metadata start"),
            Self::MissingEnd => formatter.write_str("test source has no ---*/ metadata end"),
            Self::InvalidYaml(error) => write!(formatter, "invalid test metadata YAML: {error}"),
        }
    }
}

impl std::error::Error for FrontmatterError {}

#[cfg(test)]
mod tests {
    use super::{Phase, TestFlag, TestMetadata, VariantError, VariantKind};

    #[test]
    fn parses_complete_frontmatter_and_preserves_future_flags() {
        let source = "/*---\r\ndescription: sample\r\nesid: sec-sample\r\nfeatures: [BigInt]\r\nincludes: [compareArray.js]\r\nflags: [async, CanBlockIsFalse, futureFlag]\r\nnegative:\r\n  phase: runtime\r\n  type: TypeError\r\n---*/\nthrow new TypeError();";
        let metadata = TestMetadata::parse(source).unwrap();
        assert_eq!(&*metadata.description, "sample");
        assert_eq!(metadata.negative.as_ref().unwrap().phase, Phase::Runtime);
        assert_eq!(metadata.flags[2], TestFlag::Unknown("futureFlag".into()));
        assert_eq!(
            metadata.variants(),
            Err(VariantError::UnknownFlag("futureFlag".into()))
        );
    }

    #[test]
    /// Covers the complete strict/sloppy/module/raw decision matrix, including their independent axes.
    fn expands_default_and_explicit_strictness_variants() {
        let mut metadata = TestMetadata::parse("/*---\ndescription: sample\n---*/").unwrap();
        assert_eq!(
            metadata
                .variants()
                .unwrap()
                .iter()
                .map(|variant| variant.kind)
                .collect::<Vec<_>>(),
            [VariantKind::Sloppy, VariantKind::Strict]
        );
        metadata.flags = vec![TestFlag::OnlyStrict];
        assert_eq!(metadata.variants().unwrap()[0].kind, VariantKind::Strict);
        metadata.flags = vec![TestFlag::NoStrict];
        assert_eq!(metadata.variants().unwrap()[0].kind, VariantKind::Sloppy);
        metadata.flags = vec![TestFlag::Module];
        assert_eq!(metadata.variants().unwrap()[0].kind, VariantKind::Module);
        metadata.flags = vec![TestFlag::Raw];
        assert_eq!(metadata.variants().unwrap()[0].kind, VariantKind::Raw);
        metadata.flags = vec![TestFlag::Raw, TestFlag::Module];
        let raw_module = metadata.variants().unwrap().remove(0);
        assert_eq!(raw_module.kind, VariantKind::Module);
        assert!(!raw_module.use_harness);
    }
}
